version: "3.8"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      # redis_url 可在后续配置中使用
      - REDIS_URL=redis://redis:6379/0 