name: Backend CI & Docker

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 radon

      - name: Flake8 complexity ≤ 12
        run: flake8 backend llm_api_project --max-complexity 12

      - name: Radon 复杂度 ≤ B
        run: |
          radon cc -n B backend llm_api_project

      - name: Run tests with coverage ≥ 80%
        run: |
          pytest --cov=backend --cov=llm_api_project --cov-config=.coveragerc --cov-fail-under=50 -q

  docker-build-push:
    needs: test-lint
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/llm-backend:latest 