name: Frontend CI

on:
  push:
    paths:
      - 'llm-chat-web/**'
  pull_request:
    paths:
      - 'llm-chat-web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps & build
        working-directory: ./llm-chat-web
        run: |
          npm ci --loglevel error
          npm run build --if-present 